### PR TITLE
Project setup

### LINKED ISSUE #11: Project Scaffolding & Setup

### PR DESCRIPTION
**Pull request by RoneyThomas**
Initial setup for project

### CODE REVIEW

**Review by sadeedahmed24 — APPROVED** [review]
ooga booga

**Comment by bwakessa** [comment]
poop456

**Review by bwakessa — APPROVED** [review]

**Comment by Arthur0033** [comment]
reviewed

**Review by Arthur0033 — APPROVED** [review]
A very helpful demo was included as an example of clean architecture and structure. Some principles are missing but I will make sure to add those in the final version of my code since this is example code to help us! Great work!

**Pull request merged**
