### PR TITLE
Project setup

### LINKED ISSUE #14: Add Persistence

### PR DESCRIPTION
**Pull request by RoneyThomas**
Updated gradle version and README

### CODE REVIEW

**Review by sadeedahmed24 — APPROVED** [review]
ooga booga 2.0

**Review by Arthur0033 — APPROVED** [review]
Good catch on the type in the read. me file. The h2 path seems to be working perfectly now on my end!

**Review by avinight — APPROVED** [review]
👍

**Comment by Arthur0033** [comment]
Good catch on the type in the read. me file. The h2 path seems to be working perfectly now on my end!

**Pull request merged**
