### PR TITLE
6 feature 25 recipe portion modifier

### LINKED ISSUE #6: [Feature 2.5] Recipe Portion Modifier
A portion modifier that gets and sets the portion size.

### PR DESCRIPTION
**Pull request by avinight**
### Summary
This pull request modifies the Recipe class to incorporate an editing function by introducing two methods that set the portion size and adds new ingredients to an ingredient ArrayList.

Some other changes made that are necessary for the feature implementation:
- Added Ingredient Class
- Added Editor Interface
- Added RecipeEditor Class

### CODE REVIEW

**Comment by Jun-Ars** [comment]
@avinight I believe that adding the Ingredient attribute for the Recipe class will also require it to be added to the CreateRecipe.java usecase and the RecipeValidator.java, similar to how the idgenerator was added by @bwakessa. Let's connect and make these changes before merging to the main branch.

**Review by RoneyThomas — APPROVED** [review]
Great addition. Need to add example in the Main class. But good to merge.

**Review by Arthur0033 — COMMENTED** [review]
Reviewing the pull request I understood the key concepts behind the use case. The ingredients class is written well, I see that each ingredient can be modified inside of the ingredient class through a method contained in it. One improvement that could be made is that java doc could be added to the ingredients entity to give a description of the entity as well as the constructor. The editor interface is a good idea to allows editing of the position size of the ingredient without dependency problems. Overall great work!

**Review by Jun-Ars — APPROVED** [review]
Approving now that the additional changes have been made

**Pull request merged**
