### PR TITLE
9 feature 6 creating a new account

### LINKED ISSUE #9: [Feature 6] Creating a new account
User registers by entering both a unique username and a password which meets the valid strength required. They must also successfully re-enter the password to confirm.

### PR DESCRIPTION
**Pull request by Arthur0033**
Pull request has the complete use case feature for creating a new account. Minor fixes in code problems and efficiency have been implemented to keep the feature aligned with the main code.

Smaller commits by Roney and Junaid and Bwakessa were implemented to add the missing files needed to merge with main outside of the UserCreation usecase.

### CODE REVIEW

**Review by addiaa — DISMISSED** [review]

**Review by RoneyThomas — APPROVED** [review]
Great addition. I think folder structure could be improved a bit, e.g all the interfaces in use case can be kept in its own folder. Also the all code belonging to user use case can kept in the usecase/user folder.

**Comment by RoneyThomas** [comment]
I fixed few merge conflicts. @addiaa, please review it once more.

**Review by addiaa — APPROVED** [review]
okay yea, looks good nao. thanks @RoneyThomas :DDD

**Review by bwakessa — APPROVED** [review]
looks good!

**Pull request merged**
